export const languagePacks: Record<string, Record<string, string>> = {
  pl: {
    destruct_title: 'Usunięto',
    card_server_title: 'Parametry serwera',
    card_server_desc: 'Informacje o konfiguracji PHP serwera',
    safe_extraction_info: 'Włączone zabezpieczenie "Safe Extraction" chroni serwer przed nadpisaniem ważnych skryptów i konfiguracji zabezpieczeń.',
    server_param_php: 'Parametr PHP',
    server_value_on_server: 'Wartość na serwerze',
    server_recommended: 'Zalecane',
    server_status: 'Status',
    server_optimal: 'Optymalny',
    server_compatible: 'Zgodny',
    server_warning: 'Ostrzeżenie',
    server_installed: 'Zainstalowane',
    server_missing: 'BRAK!',
    server_critical: 'Krytyczny!',
    server_active: 'Aktywne',
    server_none: 'Brak',
    server_enabled_on: 'Włączone (On)',
    server_disabled: 'Wyłączone',
    server_any: 'Dowolne',
    server_security: 'Zabezpieczenie',
    server_zip_ext: 'ZipArchive (Rozszerzenie ZIP)',
    server_zlib_comp: 'Zlib Compression (Kompresja Zlib)',
    executing_operation: 'Wykonywanie operacji',
    status_downloading: 'Pobieranie pliku (Downloading)...',
    status_extracting: 'Rozpakowywanie archiwum (Extracting)...',
    status_compressing: 'Kompresowanie katalogu (Compressing)...',
    checking_package: 'Sprawdzanie dostępności paczki...',
    package_ok: 'Paczkę można bezpiecznie pobrać (Status: OK)',
    package_error: 'Błąd: Paczka jest chwilowo niedostępna lub link wygasł.',
    package_conn_error: 'Błąd połączenia podczas weryfikacji paczki.',
    downloading_from_url: 'Pobieranie pliku z URL...',
    launching_installer: 'Uruchamianie automatycznego instalatora...',
    extracting_archive_status: 'Rozpakowywanie archiwum...',
    compressing_dir_status_short: 'Kompresowanie katalogu...',
    enter_url_alert: 'Proszę podać adres URL pliku.',
    select_app_alert: 'Proszę wybrać aplikację do zainstalowania.',
    app_desc: 'Bezpieczne zarządzanie plikami w dedykowanym folderze aplikacji',
    login_title: 'Zaloguj się',
    login_subtitle: 'Wprowadź dane uwierzytelniające',
    user: 'Użytkownik:',
    pass: 'Hasło:',
    btn_login: 'Zaloguj',
    invalid_creds: 'Nieprawidłowe dane logowania. Odmowa dostępu.',
    access_denied_post: 'Odmowa dostępu: Nieautoryzowane zapytanie POST.',
    csrf_failed: 'Odmowa dostępu: Weryfikacja tokenu CSRF nie powiodła się.',
    destruct_success_title: '✔ Sukces!',
    destruct_success_desc: 'Plik skryptu narzędziowego został trwale usunięty z systemu plików serwera.',
    destruct_failed: 'Nie udało się automatycznie usunąć pliku. Usuń go ręcznie przez FTP/SSH!',
    no_archive: 'Nie wybrano pliku archiwum.',
    unzip_success: 'Archiwum zostało pomyślnie rozpakowane. Zastosowano bezpieczne uprawnienia CHMOD.',
    unzip_error: 'Błąd rozpakowywania: ',
    zip_success: 'Archiwum zostało utworzone pomyślnie: ',
    zip_error: 'Nie udało się utworzyć archiwum zip.',
    no_delete_target: 'Nie wybrano elementów do usunięcia.',
    delete_self_denied: 'Odmowa dostępu. Nie możesz usunąć tego skryptu za pomocą tego modułu.',
    delete_dir_success: 'Katalog został pomyślnie usunięty.',
    delete_dir_error: 'Nie udało się usunąć katalogu.',
    delete_file_success: 'Plik został pomyślnie usunięty.',
    delete_file_error: 'Nie udało się usunąć pliku.',
    chmod_success: 'Pomyślnie zmieniono uprawnienia CHMOD.',
    chmod_error: 'Błąd podczas zmiany uprawnień: ',
    path_invalid: 'Odmowa bezpieczeństwa: Ścieżka docelowa jest nieprawidłowa lub próba wyjścia poza katalog aplikacji.',
    path_traversal: 'Odmowa bezpieczeństwa: Wykryto próbę ataku Path Traversal.',
    placeholder_dest_folder: 'np. podfolder',
    placeholder_suffix: 'np. backup',
    op_success: '✔ Operacja wykonana pomyślnie',
    op_error: '✕ Wystąpił błąd',
    exec_time: 'Czas wykonania: ',
    card_unzip_title: 'Rozpakuj pliki',
    card_unzip_desc: 'Ekstrakcja archiwów (.zip, .rar, .tar.gz, .7z)',
    select_archive: 'Wybierz archiwum do rozpakowania:',
    select_archive_default: '-- Wybierz plik archiwum z listy --',
    no_archives: '-- Brak archiwów w tym folderze --',
    dest_folder: 'Folder docelowy (opcjonalnie):',
    dest_folder_info: 'Pozostaw puste, aby rozpakować bezpośrednio w bieżącym katalogu skryptu. Nadpisywanie kontrolowane.',
    chmod_after_unzip: '* Uprawnienia po rozpakowaniu',
    overwrite_files: 'Opcje rozpakowywania:',
    force_unsafe: 'Wymuś wypakowanie systemowych plików (.htaccess/.env/.php)',
    btn_unzip: 'Rozpakuj',
    card_chmod_title: 'Uprawnienia CHMOD',
    card_chmod_desc: 'Zmień uprawnienia plików i katalogów w tym folderze',
    select_target: 'Wybierz katalog docelowy:',
    root_dir: '-- Katalog główny aplikacji --',
    new_matrix: 'Konfigurator nowej matrycy uprawnień:',
    folders: 'Dla katalogów:',
    files: 'Dla plików:',
    scope: 'Zakres',
    owner: 'Właściciel',
    group: 'Grupa',
    others: 'Inni',
    btn_chmod: 'Zastosuj uprawnienia',
    card_delete_title: 'Usuwanie elementów',
    card_delete_desc: 'Usuń trwale wybrane foldery i pliki ZIP',
    select_del_target: 'Wybierz element do usunięcia:',
    no_objects: 'Brak katalogów i plików ZIP do usunięcia.',
    choose_obj: '-- Wybierz obiekt z listy --',
    warning_undone: 'Uwaga: Tej operacji nie można cofnąć! Element zostanie trwale skasowany.',
    btn_delete: 'Usuń trwale',
    confirm_delete: 'Czy na pewno chcesz trwale usunąć ten element?',
    card_zip_title: 'Kompresuj katalog',
    card_zip_desc: 'Tworzenie nowych archiwów ZIP',
    select_zip_target: 'Wybierz folder do spakowania:',
    compress_all: '-- Kompresuj wszystko w folderze aplikacji --',
    suffix: 'Sufiks nazwy (opcjonalnie):',
    btn_zip: 'Utwórz ZIP',
    btn_self_destruct: '💥 SAMOZNISZCZENIE',
    confirm_self_destruct: 'Czy chcesz TRWALE usunąć ten skrypt z serwera?',
    btn_logout: 'Wyloguj',
    time_bomb_msg: '<h1>Access Denied: The script has expired and was automatically removed for security reasons.</h1>',
    timer_text: '⏱ Do automatycznego usunięcia skryptu pozostało: ',
    timer_destroying: 'PROCES NISZCZENIA...',
    zip_err_open: 'Nie można otworzyć pliku archiwum.',
    zip_err_traversal: 'Odmowa bezpieczeństwa: Wykryto próbę zapisu poza dozwolonym folderem w strukturze archiwum (Path Traversal).',
    zip_err_exists: 'Operacja przerwana: Plik już istnieje na serwerze.',
    only_zip_supported: 'Obsługiwane są formaty: .zip, .rar, .tar.gz, .7z.',
    card_download_title: 'Pobierz z URL & Instalator',
    card_download_desc: 'Pobierz dowolny plik lub automatycznie zainstaluj popularne systemy CMS',
    select_app: 'Wybierz system / bibliotekę:',
    btn_download: 'Rozpocznij pobieranie',
    btn_install: 'Uruchom instalator',
    download_url: 'Adres URL pliku:',
    download_success: 'Pomyślnie pobrano plik.',
    download_error: 'Błąd podczas pobierania pliku: ',
    install_success: 'Instalacja ukończona pomyślnie. Pliki rozpakowano i zabezpieczono.',
    install_error: 'Błąd podczas instalacji: ',
    overwrite_mode: 'Tryb nadpisywania plików:',
    overwrite_skip: 'Pomiń istniejące',
    overwrite_all: 'Nadpisz wszystkie (Niebezpieczne)',
    overwrite_older: 'Nadpisz tylko starsze',
    remote_downloader_title: '1. Remote Downloader (Pobieranie plików z URL)',
    cms_installer_title: '2. One-Click CMS & Tools Installer',
    select_app_default: '-- Wybierz system / bibliotekę --',
    save_as: 'Zapisz jako (opcjonalnie nazwa pliku/ścieżka):',
    placeholder_package: 'np. package.zip',
    install_dir: 'Katalog instalacji (opcjonalnie):',
    placeholder_install_dir: 'np. wordpress (pozostaw puste dla głównego katalogu konta)',
    folders_optgroup: 'Foldery',
    zip_optgroup: 'Pliki ZIP',
    folder_suffix: ' (Folder)',
    confirm_delete_title: 'Potwierdzenie usunięcia',
    btn_cancel: 'Anuluj',
    btn_delete_confirm: 'Usuń wybrane',
    delete_success_detail: 'Pomyślnie usunięto wskazane elementy.',
    delete_error_detail: 'Błąd podczas usuwania niektórych elementów: ',
    operation_details: 'Szczegóły operacji:',
    btn_close: 'Zamknij',
    select_del_targets: 'Wybierz elementy do usunięcia (można zaznaczyć wiele):'
  },
  en: {
    destruct_title: 'Removed',
    card_server_title: 'Server Parameters',
    card_server_desc: 'PHP configuration details of the server',
    safe_extraction_info: 'The "Safe Extraction" protection is active, preventing the overwriting of critical scripts and security configurations.',
    server_param_php: 'PHP Parameter',
    server_value_on_server: 'Value on Server',
    server_recommended: 'Recommended',
    server_status: 'Status',
    server_optimal: 'Optimal',
    server_compatible: 'Compatible',
    server_warning: 'Warning',
    server_installed: 'Installed',
    server_missing: 'MISSING!',
    server_critical: 'Critical!',
    server_active: 'Active',
    server_none: 'None',
    server_enabled_on: 'Enabled (On)',
    server_disabled: 'Disabled',
    server_any: 'Any',
    server_security: 'Security',
    server_zip_ext: 'ZipArchive (ZIP Extension)',
    server_zlib_comp: 'Zlib Compression',
    executing_operation: 'Executing operation',
    status_downloading: 'Downloading file...',
    status_extracting: 'Extracting archive...',
    status_compressing: 'Compressing directory...',
    checking_package: 'Checking package availability...',
    package_ok: 'Package can be safely downloaded (Status: OK)',
    package_error: 'Error: Package is temporarily unavailable or link expired.',
    package_conn_error: 'Connection error during package verification.',
    downloading_from_url: 'Downloading file from URL...',
    launching_installer: 'Launching automatic installer...',
    extracting_archive_status: 'Extracting archive...',
    compressing_dir_status_short: 'Compressing directory...',
    enter_url_alert: 'Please enter the file URL.',
    select_app_alert: 'Please select an application to install.',
    app_desc: 'Secure file management in a dedicated application folder',
    login_title: 'Sign In',
    login_subtitle: 'Enter your credentials',
    user: 'Username:',
    pass: 'Password:',
    btn_login: 'Login',
    invalid_creds: 'Invalid credentials. Access denied.',
    access_denied_post: 'Access Denied: Unauthorized POST Request.',
    csrf_failed: 'Access Denied: CSRF Token Validation Failed.',
    destruct_success_title: '✔ Success!',
    destruct_success_desc: 'The utility script file has been permanently deleted from the server filesystem.',
    destruct_failed: 'Failed to automatically delete the file. Please remove it manually via FTP/SSH!',
    no_archive: 'No archive file selected.',
    unzip_success: 'Archive extracted successfully. Secure CHMOD permissions applied.',
    unzip_error: 'Extraction error: ',
    zip_success: 'Archive successfully created: ',
    zip_error: 'Failed to create zip archive.',
    no_delete_target: 'No items selected for deletion.',
    delete_self_denied: 'Access denied. You cannot delete this script using this module.',
    delete_dir_success: 'Directory deleted successfully.',
    delete_dir_error: 'Failed to delete directory.',
    delete_file_success: 'File deleted successfully.',
    delete_file_error: 'Failed to delete file.',
    chmod_success: 'CHMOD permissions updated successfully.',
    chmod_error: 'CHMOD update error: ',
    path_invalid: 'Security Denial: Target path is invalid or escape attempt detected.',
    path_traversal: 'Security Denial: Path Traversal attack detected.',
    placeholder_dest_folder: 'e.g. subfolder',
    placeholder_suffix: 'e.g. backup',
    op_success: '✔ Operation completed successfully',
    op_error: '✕ An error occurred',
    exec_time: 'Execution time: ',
    card_unzip_title: 'Unzip files',
    card_unzip_desc: 'Extraction of archives (.zip, .rar, .tar.gz, .7z)',
    select_archive: 'Select archive to extract:',
    select_archive_default: '-- Select an archive file from list --',
    no_archives: '-- No archives found in this folder --',
    dest_folder: 'Destination folder (optional):',
    dest_folder_info: 'Leave empty to extract directly into the current script directory. Overwriting is controlled.',
    chmod_after_unzip: '* Permissions after extraction',
    overwrite_files: 'Extraction options:',
    force_unsafe: 'Force extraction of system files (.htaccess/.env/.php)',
    btn_unzip: 'Extract',
    card_chmod_title: 'CHMOD Permissions',
    card_chmod_desc: 'Change file and directory permissions in this folder',
    select_target: 'Select destination folder:',
    root_dir: '-- Application Root Folder --',
    new_matrix: 'Configure new permissions matrix:',
    folders: 'For folders:',
    files: 'For files:',
    scope: 'Scope',
    owner: 'Owner',
    group: 'Group',
    others: 'Others',
    btn_chmod: 'Apply permissions',
    card_delete_title: 'Delete Items',
    card_delete_desc: 'Permanently delete selected folders and ZIP files',
    select_del_target: 'Select item to delete:',
    no_objects: 'No directories or ZIP files available to delete.',
    choose_obj: '-- Select an object from list --',
    warning_undone: 'Warning: This operation cannot be undone! The item will be permanently removed.',
    btn_delete: 'Delete permanently',
    confirm_delete: 'Are you sure you want to permanently delete this item?',
    card_zip_title: 'Compress Directory',
    card_zip_desc: 'Create new ZIP archives',
    select_zip_target: 'Select folder to compress:',
    compress_all: '-- Compress everything in application folder --',
    suffix: 'Name suffix (optional):',
    btn_zip: 'Create ZIP',
    btn_self_destruct: '💥 SELF-DESTRUCT',
    confirm_self_destruct: 'Are you sure you want to PERMANENTLY delete this script from the server?',
    btn_logout: 'Logout',
    time_bomb_msg: '<h1>Access Denied: The script has expired and was automatically removed for security reasons.</h1>',
    timer_text: '⏱ Time left until automatic script deletion: ',
    timer_destroying: 'DESTROYING IN PROGRESS...',
    zip_err_open: 'Cannot open archive file.',
    zip_err_traversal: 'Security Denial: Detected attempt to write outside the allowed folder in archive structure (Path Traversal).',
    zip_err_exists: 'Operation aborted: File already exists on the server.',
    only_zip_supported: 'Supported formats are: .zip, .rar, .tar.gz, .7z.',
    card_download_title: 'Download from URL & Installer',
    card_download_desc: 'Download any file or automatically install popular CMS platforms',
    select_app: 'Select application / library:',
    btn_download: 'Start download',
    btn_install: 'Run installer',
    download_url: 'File URL:',
    download_success: 'File downloaded successfully.',
    download_error: 'Error downloading file: ',
    install_success: 'Installation completed successfully. Files extracted and secured.',
    install_error: 'Error during installation: ',
    overwrite_mode: 'File overwrite mode:',
    overwrite_skip: 'Skip existing',
    overwrite_all: 'Overwrite all (Dangerous)',
    overwrite_older: 'Overwrite only older',
    remote_downloader_title: '1. Remote Downloader (Download from URL)',
    cms_installer_title: '2. One-Click CMS & Tools Installer',
    select_app_default: '-- Select system / library --',
    save_as: 'Save as (optional filename/path):',
    placeholder_package: 'e.g. package.zip',
    install_dir: 'Installation directory (optional):',
    placeholder_install_dir: 'e.g. wordpress (leave empty for main account folder)',
    folders_optgroup: 'Folders',
    zip_optgroup: 'ZIP Files',
    folder_suffix: ' (Folder)',
    confirm_delete_title: 'Confirm Deletion',
    btn_cancel: 'Cancel',
    btn_delete_confirm: 'Delete Selected',
    delete_success_detail: 'Selected items deleted successfully.',
    delete_error_detail: 'Failed to delete some items: ',
    operation_details: 'Operation Details:',
    btn_close: 'Close',
    select_del_targets: 'Select items to delete (you can select multiple):'
  },
  de: {
    destruct_title: 'Entfernt',
    card_server_title: 'Server-Parameter',
    card_server_desc: 'Details zur PHP-Konfiguration des Servers',
    safe_extraction_info: 'Der Schutz "Safe Extraction" ist aktiv und verhindert das Überschreiben wichtiger Skripte und Sicherheitskonfigurationen.',
    server_param_php: 'PHP-Parameter',
    server_value_on_server: 'Wert auf dem Server',
    server_recommended: 'Empfohlen',
    server_status: 'Status',
    server_optimal: 'Optimal',
    server_compatible: 'Kompatibel',
    server_warning: 'Warnung',
    server_installed: 'Installiert',
    server_missing: 'FEHLT!',
    server_critical: 'Kritisch!',
    server_active: 'Aktiv',
    server_none: 'Keine',
    server_enabled_on: 'Aktiviert (On)',
    server_disabled: 'Deaktiviert',
    server_any: 'Beliebig',
    server_security: 'Sicherheit',
    server_zip_ext: 'ZipArchive (ZIP-Erweiterung)',
    server_zlib_comp: 'Zlib-Komprimierung',
    executing_operation: 'Operation wird ausgeführt',
    status_downloading: 'Datei wird heruntergeladen...',
    status_extracting: 'Archiv wird entpackt...',
    status_compressing: 'Verzeichnis wird komprimiert...',
    checking_package: 'Paketverfügbarkeit wird geprüft...',
    package_ok: 'Paket kann sicher heruntergeladen werden (Status: OK)',
    package_error: 'Fehler: Paket ist vorübergehend nicht verfügbar oder Link abgelaufen.',
    package_conn_error: 'Verbindungsfehler bei der Paketprüfung.',
    downloading_from_url: 'Datei wird von URL heruntergeladen...',
    launching_installer: 'Automatisches Installationsprogramm wird gestartet...',
    extracting_archive_status: 'Archiv wird entpackt...',
    compressing_dir_status_short: 'Verzeichnis wird komprimiert...',
    enter_url_alert: 'Bitte geben Sie die Datei-URL ein.',
    select_app_alert: 'Bitte wählen Sie eine Anwendung zur Installation aus.',
    app_desc: 'Sichere Dateiverwaltung in einem dedizierten Anwendungsordner',
    login_title: 'Anmelden',
    login_subtitle: 'Geben Sie Ihre Anmeldedaten ein',
    user: 'Benutzername:',
    pass: 'Passwort:',
    btn_login: 'Einloggen',
    invalid_creds: 'Ungültige Anmeldedaten. Zugriff verweigert.',
    access_denied_post: 'Zugriff verweigert: Unbefugte POST-Anfrage.',
    csrf_failed: 'Zugriff verweigert: CSRF-Token-Validierung fehlgeschlagen.',
    destruct_success_title: '✔ Erfolg!',
    destruct_success_desc: 'Die Skriptdatei wurde dauerhaft vom Server-Dateisystem gelöscht.',
    destruct_failed: 'Automatisches Löschen fehlgeschlagen. Bitte manuell per FTP/SSH löschen!',
    no_archive: 'Keine Archivdatei ausgewählt.',
    unzip_success: 'Archiv erfolgreich entpackt. Sichere CHMOD-Berechtigungen angewendet.',
    unzip_error: 'Fehler beim Entpacken: ',
    zip_success: 'Archiv erfolgreich erstellt: ',
    zip_error: 'Fehler beim Erstellen des ZIP-Archivs.',
    no_delete_target: 'Keine Elemente zum Löschen ausgewählt.',
    delete_self_denied: 'Zugriff verweigert. Sie können dieses Skript nicht mit diesem Modul löschen.',
    delete_dir_success: 'Verzeichnis erfolgreich gelöscht.',
    delete_dir_error: 'Verzeichnis konnte nicht gelöscht werden.',
    delete_file_success: 'Datei erfolgreich gelöscht.',
    delete_file_error: 'Datei konnte nicht gelöscht werden.',
    chmod_success: 'CHMOD-Berechtigungen erfolgreich aktualisiert.',
    chmod_error: 'Fehler beim Aktualisieren der CHMOD-Berechtigungen: ',
    path_invalid: 'Sicherheitsabweisung: Zielpfad ist ungültig oder Umgehungsversuch erkannt.',
    path_traversal: 'Sicherheitsabweisung: Path Traversal-Angriff erkannt.',
    placeholder_dest_folder: 'z.B. Unterordner',
    placeholder_suffix: 'z.B. backup',
    op_success: '✔ Operation erfolgreich abgeschlossen',
    op_error: '✕ Ein Fehler ist aufgetreten',
    exec_time: 'Ausführungszeit: ',
    card_unzip_title: 'Dateien entpacken',
    card_unzip_desc: 'Extraktion von Archiven (.zip, .rar, .tar.gz, .7z)',
    select_archive: 'Archiv zum Entpacken auswählen:',
    select_archive_default: '-- Archivdatei aus der Liste auswählen --',
    no_archives: '-- Keine Archive in diesem Ordner gefunden --',
    dest_folder: 'Zielordner (optional):',
    dest_folder_info: 'Leer lassen, um direkt in das aktuelle Skriptverzeichnis zu entpacken. Überschreiben wird kontrolliert.',
    chmod_after_unzip: '* Berechtigungen nach dem Entpacken',
    overwrite_files: 'Extraktionsoptionen:',
    force_unsafe: 'Extraktion von Systemdateien erzwingen (.htaccess/.env/.php)',
    btn_unzip: 'Entpacken',
    card_chmod_title: 'CHMOD-Berechtigungen',
    card_chmod_desc: 'Datei- und Verzeichnisberechtigungen in diesem Ordner ändern',
    select_target: 'Zielverzeichnis auswählen:',
    root_dir: '-- Hauptverzeichnis der Anwendung --',
    new_matrix: 'Neue Berechtigungsmatrix konfigurieren:',
    folders: 'Für Ordner:',
    files: 'Für Dateien:',
    scope: 'Bereich',
    owner: 'Besitzer',
    group: 'Gruppe',
    others: 'Andere',
    btn_chmod: 'Berechtigungen anwenden',
    card_delete_title: 'Elemente löschen',
    card_delete_desc: 'Ausgewählte Ordner und ZIP-Dateien dauerhaft löschen',
    select_del_target: 'Element zum Löschen auswählen:',
    no_objects: 'Keine Verzeichnisse oder ZIP-Dateien zum Löschen verfügbar.',
    choose_obj: '-- Objekt aus der Liste auswählen --',
    warning_undone: 'Warnung: Dieser Vorgang kann nicht rückgängig gemacht werden! Das Element wird dauerhaft entfernt.',
    btn_delete: 'Dauerhaft löschen',
    confirm_delete: 'Sind Sie sicher, dass Sie dieses Element dauerhaft löschen möchten?',
    card_zip_title: 'Verzeichnis komprimieren',
    card_zip_desc: 'Neue ZIP-Archive erstellen',
    select_zip_target: 'Ordner zum Komprimieren auswählen:',
    compress_all: '-- Alles im Anwendungsordner komprimieren --',
    suffix: 'Namenssuffix (optional):',
    btn_zip: 'ZIP erstellen',
    btn_self_destruct: '💥 SELBSTZERSTÖRUNG',
    confirm_self_destruct: 'Sind Sie sicher, dass Sie dieses Skript DAUERHAFT vom Server löschen möchten?',
    btn_logout: 'Abmelden',
    time_bomb_msg: '<h1>Zugriff verweigert: Das Skript ist abgelaufen und wurde aus Sicherheitsgründen automatisch entfernt.</h1>',
    timer_text: '⏱ Verbleibende Zeit bis zur automatischen Löschung: ',
    timer_destroying: 'ZERSTÖRUNG LÄUFT...',
    zip_err_open: 'Archivdatei kann nicht geöffnet werden.',
    zip_err_traversal: 'Sicherheitsabweisung: Versuch, außerhalb des zulässigen Ordners im Archiv zu schreiben (Path Traversal).',
    zip_err_exists: 'Vorgang abgebrochen: Datei existiert bereits auf dem Server.',
    only_zip_supported: 'Unterstützte Formate sind: .zip, .rar, .tar.gz, .7z.',
    card_download_title: 'Download von URL & Installer',
    card_download_desc: 'Beliebige Datei herunterladen oder beliebte CMS-Plattformen automatisch installieren',
    select_app: 'Anwendung / Bibliothek auswählen:',
    btn_download: 'Download starten',
    btn_install: 'Installer ausführen',
    download_url: 'Datei-URL:',
    download_success: 'Datei erfolgreich heruntergeladen.',
    download_error: 'Fehler beim Herunterladen der Datei: ',
    install_success: 'Installation erfolgreich abgeschlossen. Dateien extrahiert und gesichert.',
    install_error: 'Fehler während der Installation: ',
    overwrite_mode: 'Datei-Überschreibmodus:',
    overwrite_skip: 'Existierende überspringen',
    overwrite_all: 'Alle überschreiben (Gefährlich)',
    overwrite_older: 'Nur ältere überschreiben',
    remote_downloader_title: '1. Remote Downloader (Download von URL)',
    cms_installer_title: '2. One-Click CMS & Tools Installer',
    select_app_default: '-- System / Bibliothek auswählen --',
    save_as: 'Speichern unter (optionaler Dateiname/Pfad):',
    placeholder_package: 'z.B. package.zip',
    install_dir: 'Installationsverzeichnis (optional):',
    placeholder_install_dir: 'z.B. wordpress (leer lassen für Hauptkontoordner)',
    folders_optgroup: 'Ordner',
    zip_optgroup: 'ZIP-Dateien',
    folder_suffix: ' (Ordner)',
    confirm_delete_title: 'Löschen bestätigen',
    btn_cancel: 'Abbrechen',
    btn_delete_confirm: 'Auswahl löschen',
    delete_success_detail: 'Ausgewählte Elemente erfolgreich gelöscht.',
    delete_error_detail: 'Einige Elemente konnten nicht gelöscht werden: ',
    operation_details: 'Details zum Vorgang:',
    btn_close: 'Schließen',
    select_del_targets: 'Elemente zum Löschen auswählen (Mehrfachauswahl möglich):'
  },
  es: {
    destruct_title: 'Eliminado',
    card_server_title: 'Parámetros del Servidor',
    card_server_desc: 'Detalles de configuración PHP del servidor',
    safe_extraction_info: 'La protección "Safe Extraction" está activa, evitando la sobrescritura de scripts críticos y configuraciones de seguridad.',
    server_param_php: 'Parámetro PHP',
    server_value_on_server: 'Valor en el servidor',
    server_recommended: 'Recomendado',
    server_status: 'Estado',
    server_optimal: 'Óptimo',
    server_compatible: 'Compatible',
    server_warning: 'Advertencia',
    server_installed: 'Instalado',
    server_missing: '¡FALTA!',
    server_critical: '¡Crítico!',
    server_active: 'Activo',
    server_none: 'Ninguno',
    server_enabled_on: 'Habilitado (On)',
    server_disabled: 'Deshabilitado',
    server_any: 'Cualquiera',
    server_security: 'Seguridad',
    server_zip_ext: 'ZipArchive (Extensión ZIP)',
    server_zlib_comp: 'Compresión Zlib',
    executing_operation: 'Ejecutando operación',
    status_downloading: 'Descargando archivo...',
    status_extracting: 'Descomprimiendo archivo...',
    status_compressing: 'Comprimiendo directorio...',
    checking_package: 'Comprobando disponibilidad del paquete...',
    package_ok: 'El paquete se puede descargar de forma segura (Estado: OK)',
    package_error: 'Error: El paquete no está disponible temporalmente o el enlace ha caducado.',
    package_conn_error: 'Error de conexión durante la verificación del paquete.',
    downloading_from_url: 'Descargando archivo desde URL...',
    launching_installer: 'Iniciando instalador automático...',
    extracting_archive_status: 'Descomprimiendo archivo...',
    compressing_dir_status_short: 'Comprimiendo directorio...',
    enter_url_alert: 'Por favor, introduzca la URL del archivo.',
    select_app_alert: 'Por favor, seleccione una aplicación para instalar.',
    app_desc: 'Gestión segura de archivos en una carpeta de aplicación dedicada',
    login_title: 'Iniciar Sesión',
    login_subtitle: 'Introduzca sus credenciales',
    user: 'Usuario:',
    pass: 'Contraseña:',
    btn_login: 'Entrar',
    invalid_creds: 'Credenciales inválidas. Acceso denegado.',
    access_denied_post: 'Acceso denegado: Solicitud POST no autorizada.',
    csrf_failed: 'Acceso denegado: Falló la validación del token CSRF.',
    destruct_success_title: '✔ ¡Éxito!',
    destruct_success_desc: 'El archivo del script de utilidad ha sido eliminado permanentemente del servidor.',
    destruct_failed: 'Fallo al eliminar automáticamente. ¡Elimínelo manualmente por FTP/SSH!',
    no_archive: 'No se ha seleccionado ningún archivo.',
    unzip_success: 'Archivo descomprimido con éxito. Permisos CHMOD seguros aplicados.',
    unzip_error: 'Error al descomprimir: ',
    zip_success: 'Archivo creado con éxito: ',
    zip_error: 'Fallo al crear el archivo ZIP.',
    no_delete_target: 'No se seleccionaron elementos para eliminar.',
    delete_self_denied: 'Acceso denegado. No puede eliminar este script usando este módulo.',
    delete_dir_success: 'Directorio eliminado con éxito.',
    delete_dir_error: 'Fallo al eliminar el directorio.',
    delete_file_success: 'Archivo eliminado con éxito.',
    delete_file_error: 'Fallo al eliminar el archivo.',
    chmod_success: 'Permisos CHMOD actualizados con éxito.',
    chmod_error: 'Error al actualizar los permisos CHMOD: ',
    path_invalid: 'Denegación de seguridad: La ruta de destino no es válida o se detectó un intento de escape.',
    path_traversal: 'Denegación de seguridad: Se detectó un ataque de Path Traversal.',
    placeholder_dest_folder: 'por ejemplo, subcarpeta',
    placeholder_suffix: 'por ejemplo, backup',
    op_success: '✔ Operación completada con éxito',
    op_error: '✕ Ocurrió un error',
    exec_time: 'Tiempo de ejecución: ',
    card_unzip_title: 'Descomprimir archivos',
    card_unzip_desc: 'Extracción de archivos (.zip, .rar, .tar.gz, .7z)',
    select_archive: 'Seleccione el archivo a extraer:',
    select_archive_default: '-- Seleccione un archivo de la lista --',
    no_archives: '-- No se encontraron archivos en esta carpeta --',
    dest_folder: 'Carpeta de destino (opcional):',
    dest_folder_info: 'Dejar en blanco para extraer directamente en el directorio del script actual. Sobrescritura controlada.',
    chmod_after_unzip: '* Permisos después de la extracción',
    overwrite_files: 'Opciones de extracción:',
    force_unsafe: 'Forzar la extracción de archivos del sistema (.htaccess/.env/.php)',
    btn_unzip: 'Extraer',
    card_chmod_title: 'Permisos CHMOD',
    card_chmod_desc: 'Cambiar permisos de archivos y directorios en esta carpeta',
    select_target: 'Seleccione directorio de destino:',
    root_dir: '-- Directorio raíz de la aplicación --',
    new_matrix: 'Configurar nueva matriz de permisos:',
    folders: 'Para carpetas:',
    files: 'Para archivos:',
    scope: 'Ámbito',
    owner: 'Propietario',
    group: 'Grupo',
    others: 'Otros',
    btn_chmod: 'Aplicar permisos',
    card_delete_title: 'Eliminar elementos',
    card_delete_desc: 'Eliminar permanentemente las carpetas y archivos ZIP seleccionados',
    select_del_target: 'Seleccione elemento a eliminar:',
    no_objects: 'No hay directorios o archivos ZIP disponibles para eliminar.',
    choose_obj: '-- Seleccione un objeto de la lista --',
    warning_undone: 'Advertencia: ¡Esta operación no se puede deshacer! El elemento se eliminará permanentemente.',
    btn_delete: 'Eliminar permanentemente',
    confirm_delete: '¿Está seguro de que desea eliminar permanentemente este elemento?',
    card_zip_title: 'Comprimir directorio',
    card_zip_desc: 'Crear nuevos archivos ZIP',
    select_zip_target: 'Seleccione carpeta a comprimir:',
    compress_all: '-- Comprimir todo en la carpeta de la aplicación --',
    suffix: 'Sufijo del nombre (opcional):',
    btn_zip: 'Crear ZIP',
    btn_self_destruct: '💥 AUTODESTRUCCIÓN',
    confirm_self_destruct: '¿Está seguro de que desea eliminar PERMANENTEMENTE este script del servidor?',
    btn_logout: 'Cerrar sesión',
    time_bomb_msg: '<h1>Acceso denegado: El script ha expirado y se ha eliminado automáticamente por razones de seguridad.</h1>',
    timer_text: '⏱ Tiempo restante hasta la autodestrucción: ',
    timer_destroying: 'DESTRUCCIÓN EN PROGRESO...',
    zip_err_open: 'No se puede abrir el archivo.',
    zip_err_traversal: 'Denegación de seguridad: Intento de escribir fuera de la carpeta permitida (Path Traversal).',
    zip_err_exists: 'Operación abortada: El archivo ya existe en el servidor.',
    only_zip_supported: 'Formatos admitidos: .zip, .rar, .tar.gz, .7z.',
    card_download_title: 'Descarga de URL & Instalador',
    card_download_desc: 'Descargue cualquier archivo o instale automáticamente plataformas CMS populares',
    select_app: 'Seleccione aplicación / biblioteca:',
    btn_download: 'Iniciar descarga',
    btn_install: 'Ejecutar instalador',
    download_url: 'URL del archivo:',
    download_success: 'Archivo descargado con éxito.',
    download_error: 'Error al descargar el archivo: ',
    install_success: 'Instalación completada con éxito. Archivos extraídos y asegurados.',
    install_error: 'Error durante la instalación: ',
    overwrite_mode: 'Modo de sobrescritura de archivos:',
    overwrite_skip: 'Omitir existentes',
    overwrite_all: 'Sobrescribir todos (Peligroso)',
    overwrite_older: 'Sobrescribir solo más antiguos',
    remote_downloader_title: '1. Remote Downloader (Descargar desde URL)',
    cms_installer_title: '2. One-Click CMS & Tools Installer',
    select_app_default: '-- Seleccionar sistema / biblioteca --',
    save_as: 'Guardar como (nombre de archivo/ruta opcional):',
    placeholder_package: 'ej. package.zip',
    install_dir: 'Directorio de instalación (opcional):',
    placeholder_install_dir: 'ej. wordpress (dejar vacío para carpeta principal)',
    folders_optgroup: 'Carpetas',
    zip_optgroup: 'Archivos ZIP',
    folder_suffix: ' (Carpeta)',
    confirm_delete_title: 'Confirmar eliminación',
    btn_cancel: 'Cancelar',
    btn_delete_confirm: 'Eliminar seleccionados',
    delete_success_detail: 'Elementos seleccionados eliminados con éxito.',
    delete_error_detail: 'Fallo al eliminar algunos elementos: ',
    operation_details: 'Detalles de la operación:',
    btn_close: 'Cerrar',
    select_del_targets: 'Seleccione elementos a eliminar (selección múltiple permitida):'
  },
  fr: {
    destruct_title: 'Supprimé',
    card_server_title: 'Paramètres du Serveur',
    card_server_desc: 'Détails de configuration PHP du serveur',
    safe_extraction_info: 'La protection "Safe Extraction" est active, empêchant l\'écrasement des scripts critiques et des configurations de sécurité.',
    server_param_php: 'Paramètre PHP',
    server_value_on_server: 'Valeur sur le serveur',
    server_recommended: 'Recommandé',
    server_status: 'Statut',
    server_optimal: 'Optimal',
    server_compatible: 'Compatible',
    server_warning: 'Avertissement',
    server_installed: 'Installé',
    server_missing: 'MANQUANT !',
    server_critical: 'Critique !',
    server_active: 'Actif',
    server_none: 'Aucun',
    server_enabled_on: 'Activé (On)',
    server_disabled: 'Désactivé',
    server_any: 'Indifférent',
    server_security: 'Sécurité',
    server_zip_ext: 'ZipArchive (Extension ZIP)',
    server_zlib_comp: 'Compression Zlib',
    executing_operation: 'Exécution de l\'opération',
    status_downloading: 'Téléchargement du fichier...',
    status_extracting: 'Extraction de l\'archive...',
    status_compressing: 'Compression du dossier...',
    checking_package: 'Vérification de la disponibilité du paquet...',
    package_ok: 'Le paquet peut être téléchargé en toute sécurité (Statut : OK)',
    package_error: 'Erreur : Le paquet est temporairement indisponible ou le lien a expiré.',
    package_conn_error: 'Erreur de connexion lors de la vérification du paquet.',
    downloading_from_url: 'Téléchargement du fichier depuis l\'URL...',
    launching_installer: 'Lancement de l\'installateur automatique...',
    extracting_archive_status: 'Extraction de l\'archive...',
    compressing_dir_status_short: 'Compression du dossier...',
    enter_url_alert: 'Veuillez saisir l\'URL du fichier.',
    select_app_alert: 'Veuillez sélectionner une application à installer.',
    app_desc: 'Gestion sécurisée des fichiers dans un dossier d\'application dédié',
    login_title: 'Se Connecter',
    login_subtitle: 'Entrez vos identifiants',
    user: 'Utilisateur :',
    pass: 'Mot de passe :',
    btn_login: 'Connexion',
    invalid_creds: 'Identifiants invalides. Accès refusé.',
    access_denied_post: 'Accès refusé : Requête POST non autorisée.',
    csrf_failed: 'Accès refusé : Échec de validation du jeton CSRF.',
    destruct_success_title: '✔ Succès !',
    destruct_success_desc: 'Le script utilitaire a été définitivement supprimé du serveur.',
    destruct_failed: 'Échec de la suppression automatique. Veuillez le supprimer manuellement via FTP/SSH !',
    no_archive: 'Aucun fichier archive sélectionné.',
    unzip_success: 'Archive extraite avec succès. Permissions CHMOD sécurisées appliquées.',
    unzip_error: 'Erreur lors de l\'extraction : ',
    zip_success: 'Archive créée avec succès : ',
    zip_error: 'Échec de la création de l\'archive ZIP.',
    no_delete_target: 'Aucun élément sélectionné pour la suppression.',
    delete_self_denied: 'Accès refusé. Vous ne pouvez pas supprimer ce script avec ce module.',
    delete_dir_success: 'Dossier supprimé avec succès.',
    delete_dir_error: 'Échec de la suppression du dossier.',
    delete_file_success: 'Fichier supprimé avec succès.',
    delete_file_error: 'Échec de la suppression du fichier.',
    chmod_success: 'Permissions CHMOD mises à jour avec succès.',
    chmod_error: 'Erreur lors de la modification des permissions CHMOD : ',
    path_invalid: 'Refus de sécurité : Le chemin cible est invalide ou tentative de contournement détectée.',
    path_traversal: 'Refus de sécurité : Attaque Path Traversal détectée.',
    placeholder_dest_folder: 'ex. sous-dossier',
    placeholder_suffix: 'ex. backup',
    op_success: '✔ Opération terminée avec succès',
    op_error: '✕ Une erreur est survenue',
    exec_time: 'Temps d\'exécution : ',
    card_unzip_title: 'Extraire des fichiers',
    card_unzip_desc: 'Extraction d\'archives (.zip, .rar, .tar.gz, .7z)',
    select_archive: 'Sélectionnez l\'archive à extraire :',
    select_archive_default: '-- Sélectionnez un fichier archive de la liste --',
    no_archives: '-- Aucun fichier archive trouvé dans ce dossier --',
    dest_folder: 'Dossier de destination (optionnel) :',
    dest_folder_info: 'Laisser vide pour extraire directement dans le dossier du script actuel. Écrasement contrôlé.',
    chmod_after_unzip: '* Permissions après extraction',
    overwrite_files: 'Options d\'extraction :',
    force_unsafe: 'Forcer l\'extraction des fichiers système (.htaccess/.env/.php)',
    btn_unzip: 'Extraire',
    card_chmod_title: 'Permissions CHMOD',
    card_chmod_desc: 'Modifier les permissions des fichiers et dossiers dans ce répertoire',
    select_target: 'Sélectionnez le dossier cible :',
    root_dir: '-- Répertoire racine de l\'application --',
    new_matrix: 'Configurer la nouvelle matrice de permissions :',
    folders: 'Pour les dossiers :',
    files: 'Pour les fichiers :',
    scope: 'Portée',
    owner: 'Propriétaire',
    group: 'Groupe',
    others: 'Autres',
    btn_chmod: 'Appliquer les permissions',
    card_delete_title: 'Supprimer des éléments',
    card_delete_desc: 'Supprimer définitivement les dossiers et fichiers ZIP sélectionnés',
    select_del_target: 'Sélectionnez l\'élément à supprimer :',
    no_objects: 'Aucun dossier ou fichier ZIP disponible pour la suppression.',
    choose_obj: '-- Sélectionnez un objet de la liste --',
    warning_undone: 'Attention : Cette opération est irréversible ! L\'élément sera définitivement supprimé.',
    btn_delete: 'Supprimer définitivement',
    confirm_delete: 'Êtes-vous sûr de vouloir supprimer définitivement cet élément ?',
    card_zip_title: 'Compresser un dossier',
    card_zip_desc: 'Créer de nouvelles archives ZIP',
    select_zip_target: 'Sélectionnez le dossier à compresser :',
    compress_all: '-- Compresser tout le contenu du dossier applicatif --',
    suffix: 'Suffixe du nom (optionnel) :',
    btn_zip: 'Créer le ZIP',
    btn_self_destruct: '💥 AUTODESTRUCTION',
    confirm_self_destruct: 'Êtes-vous sûr de vouloir supprimer DÉFINITIVEMENT ce script du serveur ?',
    btn_logout: 'Se déconnecter',
    time_bomb_msg: '<h1>Accès refusé : Le script a expiré et a été automatiquement supprimé pour des raisons de sécurité.</h1>',
    timer_text: '⏱ Temps restant avant l\'autodestruction : ',
    timer_destroying: 'DESTRUCTION EN COURS...',
    zip_err_open: 'Impossible d\'ouvrir le fichier archive.',
    zip_err_traversal: 'Refus de sécurité : Tentative d\'écriture en dehors du dossier autorisé dans l\'archive (Path Traversal).',
    zip_err_exists: 'Opération annulée : Le fichier existe déjà sur le serveur.',
    only_zip_supported: 'Les formats supportés sont : .zip, .rar, .tar.gz, .7z.',
    card_download_title: 'Téléchargement URL & Installateur',
    card_download_desc: 'Télécharger n\'importe quel fichier ou installer automatiquement des CMS populaires',
    select_app: 'Sélectionnez l\'application / bibliothèque :',
    btn_download: 'Démarrer le téléchargement',
    btn_install: 'Lancer l\'installateur',
    download_url: 'URL du fichier :',
    download_success: 'Fichier téléchargé avec succès.',
    download_error: 'Erreur lors du téléchargement du fichier : ',
    install_success: 'Installation terminée avec succès. Fichiers extraits et sécurisés.',
    install_error: 'Erreur lors de l\'installation : ',
    overwrite_mode: 'Mode d\'écrasement des fichiers :',
    overwrite_skip: 'Ignorer les existants',
    overwrite_all: 'Tout écraser (Dangereux)',
    overwrite_older: 'Écraser uniquement les plus anciens',
    remote_downloader_title: '1. Remote Downloader (Télécharger depuis une URL)',
    cms_installer_title: '2. One-Click CMS & Tools Installer',
    select_app_default: '-- Sélectionner système / bibliothèque --',
    save_as: 'Enregistrer sous (nom de fichier/chemin optionnel) :',
    placeholder_package: 'ex. package.zip',
    install_dir: 'Dossier d\'installation (optionnel) :',
    placeholder_install_dir: 'ex. wordpress (laisser vide pour le dossier principal)',
    folders_optgroup: 'Dossiers',
    zip_optgroup: 'Fichiers ZIP',
    folder_suffix: ' (Dossier)',
    confirm_delete_title: 'Confirmer la suppression',
    btn_cancel: 'Annuler',
    btn_delete_confirm: 'Supprimer la sélection',
    delete_success_detail: 'Éléments sélectionnés supprimés avec succès.',
    delete_error_detail: 'Impossible de supprimer certains éléments : ',
    operation_details: 'Détails de l\'opération :',
    btn_close: 'Fermer',
    select_del_targets: 'Sélectionnez les éléments à supprimer (plusieurs sélections possibles) :'
  },
  it: {
    destruct_title: 'Rimosso',
    card_server_title: 'Parametri del Server',
    card_server_desc: 'Dettagli di configurazione PHP del server',
    safe_extraction_info: 'La protezione "Safe Extraction" è attiva, impedendo la sovrascrittura di script critici e configurazioni di sicurezza.',
    server_param_php: 'Parametro PHP',
    server_value_on_server: 'Valore sul server',
    server_recommended: 'Consigliato',
    server_status: 'Stato',
    server_optimal: 'Ottimale',
    server_compatible: 'Compatibile',
    server_warning: 'Attenzione',
    server_installed: 'Installato',
    server_missing: 'MANCANTE!',
    server_critical: 'Critico!',
    server_active: 'Attivo',
    server_none: 'Nessuno',
    server_enabled_on: 'Abilitato (On)',
    server_disabled: 'Disabilitato',
    server_any: 'Qualsiasi',
    server_security: 'Sicurezza',
    server_zip_ext: 'ZipArchive (Estensione ZIP)',
    server_zlib_comp: 'Compressione Zlib',
    executing_operation: 'Esecuzione dell\'operazione',
    status_downloading: 'Download del file...',
    status_extracting: 'Estrazione dell\'archivio...',
    status_compressing: 'Compressione della directory...',
    checking_package: 'Verifica della disponibilità del pacchetto...',
    package_ok: 'Il pacchetto può essere scaricato in sicurezza (Stato: OK)',
    package_error: 'Errore: Il pacchetto è temporaneamente non disponibile o il link è scaduto.',
    package_conn_error: 'Errore di connessione durante la verifica del pacchetto.',
    downloading_from_url: 'Download del file da URL...',
    launching_installer: 'Avvio dell\'installatore automatico...',
    extracting_archive_status: 'Estrazione dell\'archivio...',
    compressing_dir_status_short: 'Compressione della directory...',
    enter_url_alert: 'Si prega di inserire l\'URL del file.',
    select_app_alert: 'Si prega di selezionare un\'applicazione da installare.',
    app_desc: 'Gestione sicura dei file in una cartella dell\'applicazione dedicata',
    login_title: 'Accedi',
    login_subtitle: 'Inserisci le tue credenziali',
    user: 'Nome utente:',
    pass: 'Password:',
    btn_login: 'Accedi',
    invalid_creds: 'Credenziali non valide. Accesso negato.',
    access_denied_post: 'Accesso negato: Richiesta POST non autorizzata.',
    csrf_failed: 'Accesso negato: Validazione del token CSRF fallita.',
    destruct_success_title: '✔ Successo!',
    destruct_success_desc: 'Il file dello script è stato eliminato definitivamente dal filesystem del server.',
    destruct_failed: 'Eliminazione automatica fallita. Rimuoverlo manualmente tramite FTP/SSH!',
    no_archive: 'Nessun file archivio selezionato.',
    unzip_success: 'Archivio estratto con successo. Applicati permessi CHMOD sicuri.',
    unzip_error: 'Errore durante l\'estrazione: ',
    zip_success: 'Archivio creato con successo: ',
    zip_error: 'Impossibile creare l\'archivio ZIP.',
    no_delete_target: 'Nessun elemento selezionato per l\'eliminazione.',
    delete_self_denied: 'Accesso negato. Non puoi eliminare questo script usando questo modulo.',
    delete_dir_success: 'Directory eliminata con successo.',
    delete_dir_error: 'Impossibile eliminare la directory.',
    delete_file_success: 'File eliminato con successo.',
    delete_file_error: 'Impossibile eliminare il file.',
    chmod_success: 'Permessi CHMOD aggiornati con successo.',
    chmod_error: 'Errore durante l\'aggiornamento dei permessi CHMOD: ',
    path_invalid: 'Rifiuto di sicurezza: Il percorso di destinazione non è valido o rilevato tentativo di escape.',
    path_traversal: 'Rifiuto di sicurezza: Rilevato attacco Path Traversal.',
    placeholder_dest_folder: 'es. sottocartella',
    placeholder_suffix: 'es. backup',
    op_success: '✔ Operazione completata con successo',
    op_error: '✕ Si è verificato un errore',
    exec_time: 'Tempo di esecuzione: ',
    card_unzip_title: 'Estrai file',
    card_unzip_desc: 'Estrazione di archivi (.zip, .rar, .tar.gz, .7z)',
    select_archive: 'Seleziona archivio da estrarre:',
    select_archive_default: '-- Seleziona un file archivio dalla lista --',
    no_archives: '-- Nessun archivio trovato in questa cartella --',
    dest_folder: 'Cartella di destinazione (opzionale):',
    dest_folder_info: 'Lascia vuoto per estrarre direttamente nella cartella dello script corrente. Sovrascrittura controllata.',
    chmod_after_unzip: '* Permessi dopo l\'estrazione',
    overwrite_files: 'Opzioni di estrazione:',
    force_unsafe: 'Forza estrazione dei file di sistema (.htaccess/.env/.php)',
    btn_unzip: 'Estrai',
    card_chmod_title: 'Permessi CHMOD',
    card_chmod_desc: 'Modifica i permessi di file e directory in questa cartella',
    select_target: 'Seleziona directory di destinazione:',
    root_dir: '-- Cartella principale dell\'applicazione --',
    new_matrix: 'Configura nuova matrice dei permessi:',
    folders: 'Per le cartelle:',
    files: 'Per i file:',
    scope: 'Ambito',
    owner: 'Proprietario',
    group: 'Gruppo',
    others: 'Altri',
    btn_chmod: 'Applica permessi',
    card_delete_title: 'Elimina elementi',
    card_delete_desc: 'Elimina permanentemente le cartelle e i file ZIP selezionati',
    select_del_target: 'Seleziona elemento da eliminare:',
    no_objects: 'Nessuna directory o file ZIP disponibile per l\'eliminazione.',
    choose_obj: '-- Seleziona un oggetto dalla lista --',
    warning_undone: 'Attenzione: Questa operazione non può essere annullata! L\'elemento verrà rimosso permanentemente.',
    btn_delete: 'Elimina permanentemente',
    confirm_delete: 'Sei sicuro di voler eliminare permanentemente questo elemento?',
    card_zip_title: 'Comprimi directory',
    card_zip_desc: 'Crea nuovi archivi ZIP',
    select_zip_target: 'Seleziona cartella da comprimere:',
    compress_all: '-- Comprimi tutto nella cartella dell\'applicazione --',
    suffix: 'Suffisso del nome (opzionale):',
    btn_zip: 'Crea ZIP',
    btn_self_destruct: '💥 AUTODISTRUZIONE',
    confirm_self_destruct: 'Sei sicuro di voler eliminare PERMANENTEMENTE questo script dal server?',
    btn_logout: 'Disconnetti',
    time_bomb_msg: '<h1>Accesso negato: Lo script è scaduto ed è stato rimosso automaticamente per motivi di sicurezza.</h1>',
    timer_text: '⏱ Tempo rimanente all\'autodistruzione: ',
    timer_destroying: 'DISTRUZIONE IN CORSO...',
    zip_err_open: 'Impossibile aprire il file archivio.',
    zip_err_traversal: 'Rifiuto di sicurezza: Rilevato tentativo di scrivere fuori dalla cartella consentita (Path Traversal).',
    zip_err_exists: 'Operazione interrotta: Il file esiste già sul server.',
    only_zip_supported: 'I formati supportati sono: .zip, .rar, .tar.gz, .7z.',
    card_download_title: 'Download da URL & Installatore',
    card_download_desc: 'Scarica qualsiasi file o installa automaticamente piattaforme CMS popolari',
    select_app: 'Seleziona applicazione / libreria:',
    btn_download: 'Avvia download',
    btn_install: 'Esegui installatore',
    download_url: 'URL del file:',
    download_success: 'File scaricato con successo.',
    download_error: 'Errore durante il download del file: ',
    install_success: 'Installazione completata con successo. File estratti e protetti.',
    install_error: 'Errore durante l\'installazione: ',
    overwrite_mode: 'Modalità sovrascrittura file:',
    overwrite_skip: 'Salta esistenti',
    overwrite_all: 'Sovrascrivi tutto (Pericoloso)',
    overwrite_older: 'Sovrascrivi solo più vecchi',
    remote_downloader_title: '1. Remote Downloader (Scarica da URL)',
    cms_installer_title: '2. One-Click CMS & Tools Installer',
    select_app_default: '-- Seleziona sistema / biblioteca --',
    save_as: 'Salva come (nome file/percorso opzionale):',
    placeholder_package: 'es. package.zip',
    install_dir: 'Directory di installazione (opzionale):',
    placeholder_install_dir: 'es. wordpress (lascia vuoto per la cartella principale)',
    folders_optgroup: 'Cartelle',
    zip_optgroup: 'File ZIP',
    folder_suffix: ' (Cartella)',
    confirm_delete_title: 'Conferma eliminazione',
    btn_cancel: 'Annulla',
    btn_delete_confirm: 'Elimina selezionati',
    delete_success_detail: 'Elementi selezionati eliminati con successo.',
    delete_error_detail: 'Impossibile eliminare alcuni elementi: ',
    operation_details: 'Dettagli dell\'operazione:',
    btn_close: 'Chiudi',
    select_del_targets: 'Seleziona elementi da eliminare (selezione multipla consentita):'
  },
  pt: {
    destruct_title: 'Removido',
    card_server_title: 'Parâmetros do Servidor',
    card_server_desc: 'Detalhes de configuração PHP do servidor',
    safe_extraction_info: 'A proteção "Safe Extraction" está ativa, evitando a sobrescrita de scripts críticos e configurações de segurança.',
    server_param_php: 'Parâmetro PHP',
    server_value_on_server: 'Valor no servidor',
    server_recommended: 'Recomendado',
    server_status: 'Estado',
    server_optimal: 'Ideal',
    server_compatible: 'Compatível',
    server_warning: 'Aviso',
    server_installed: 'Instalado',
    server_missing: 'FALTANDO!',
    server_critical: 'Crítico!',
    server_active: 'Ativo',
    server_none: 'Nenhum',
    server_enabled_on: 'Ativado (On)',
    server_disabled: 'Desativado',
    server_any: 'Qualquer',
    server_security: 'Segurança',
    server_zip_ext: 'ZipArchive (Extensão ZIP)',
    server_zlib_comp: 'Compressão Zlib',
    executing_operation: 'Executando operação',
    status_downloading: 'Descarregando arquivo...',
    status_extracting: 'Extraindo arquivo...',
    status_compressing: 'Comprimindo diretório...',
    checking_package: 'Verificando a disponibilidade do pacote...',
    package_ok: 'O pacote pode ser descarregado com segurança (Estado: OK)',
    package_error: 'Erro: O pacote está temporariamente indisponível ou o link expirou.',
    package_conn_error: 'Erro de conexão durante a verificação do pacote.',
    downloading_from_url: 'Descarregando arquivo a partir do URL...',
    launching_installer: 'Iniciando o instalador automático...',
    extracting_archive_status: 'Extraindo arquivo...',
    compressing_dir_status_short: 'Comprimindo diretório...',
    enter_url_alert: 'Por favor, insira o URL do arquivo.',
    select_app_alert: 'Por favor, selecione um aplicativo para instalar.',
    app_desc: 'Gestão segura de ficheiros numa pasta de aplicação dedicada',
    login_title: 'Entrar',
    login_subtitle: 'Introduza as suas credenciais',
    user: 'Nome de utilizador:',
    pass: 'Palavra-passe:',
    btn_login: 'Entrar',
    invalid_creds: 'Credenciais inválidas. Acesso denegado.',
    access_denied_post: 'Acesso negado: Pedido POST não autorizado.',
    csrf_failed: 'Acesso negado: Validação do token CSRF falhou.',
    destruct_success_title: '✔ Sucesso!',
    destruct_success_desc: 'O ficheiro do script foi permanentemente eliminado do servidor.',
    destruct_failed: 'Falha ao eliminar automaticamente. Elimine-o manualmente via FTP/SSH!',
    no_archive: 'Nenhum ficheiro de arquivo selecionado.',
    unzip_success: 'Arquivo extraído com sucesso. Permissões CHMOD seguras aplicadas.',
    unzip_error: 'Erro ao extrair: ',
    zip_success: 'Arquivo criado com sucesso: ',
    zip_error: 'Falha ao criar o arquivo ZIP.',
    no_delete_target: 'Nenhum item selecionado para eliminação.',
    delete_self_denied: 'Acesso denied. Não pode eliminar este script usando este módulo.',
    delete_dir_success: 'Diretório eliminado com sucesso.',
    delete_dir_error: 'Falha ao eliminar o diretório.',
    delete_file_success: 'Ficheiro eliminado com sucesso.',
    delete_file_error: 'Falha ao eliminar o ficheiro.',
    chmod_success: 'Permissões CHMOD atualizadas com sucesso.',
    chmod_error: 'Erro ao atualizar as permissões CHMOD: ',
    path_invalid: 'Negação de segurança: O caminho de destino é inválido ou foi detetada uma tentativa de fuga.',
    path_traversal: 'Negação de segurança: Detetado ataque de Path Traversal.',
    placeholder_dest_folder: 'ex. subpasta',
    placeholder_suffix: 'ex. backup',
    op_success: '✔ Operação concluída com sucesso',
    op_error: '✕ Ocorreu um erro',
    exec_time: 'Tempo de execução: ',
    card_unzip_title: 'Extrair ficheiros',
    card_unzip_desc: 'Extração de arquivos (.zip, .rar, .tar.gz, .7z)',
    select_archive: 'Selecione o arquivo a extrair:',
    select_archive_default: '-- Selecione um ficheiro de arquivo da lista --',
    no_archives: '-- Nenhum arquivo encontrado nesta pasta --',
    dest_folder: 'Pasta de destino (opcional):',
    dest_folder_info: 'Deixe em branco para extrair diretamente no diretório do script atual. Sobragravação controlada.',
    chmod_after_unzip: '* Permissões após extração',
    overwrite_files: 'Opções de extração:',
    force_unsafe: 'Forçar extração de ficheiros de sistema (.htaccess/.env/.php)',
    btn_unzip: 'Extrair',
    card_chmod_title: 'Permissões CHMOD',
    card_chmod_desc: 'Alterar permissões de ficheiros e diretórios nesta pasta',
    select_target: 'Selecione o diretório de destino:',
    root_dir: '-- Diretório raiz da aplicação --',
    new_matrix: 'Configurar nova matriz de permissões:',
    folders: 'Para pastas:',
    files: 'Para ficheiros:',
    scope: 'Âmbito',
    owner: 'Proprietário',
    group: 'Grupo',
    others: 'Outros',
    btn_chmod: 'Aplicar permissions',
    card_delete_title: 'Eliminar itens',
    card_delete_desc: 'Eliminar permanentemente as pastas e ficheiros ZIP selecionados',
    select_del_target: 'Selecione o item a eliminar:',
    no_objects: 'Nenhum diretório ou ficheiro ZIP disponível para eliminação.',
    choose_obj: '-- Selecione um objeto da lista --',
    warning_undone: 'Aviso: Esta operação não pode ser anulada! O item será permanentemente removido.',
    btn_delete: 'Eliminar permanentemente',
    confirm_delete: 'Tem a certeza de que deseja eliminar permanentemente este item?',
    card_zip_title: 'Comprimir diretório',
    card_zip_desc: 'Criar novos arquivos ZIP',
    select_zip_target: 'Selecione a pasta a comprimir:',
    compress_all: '-- Comprimir tudo na pasta da aplicação --',
    suffix: 'Sufixo do nome (opcional):',
    btn_zip: 'Criar ZIP',
    btn_self_destruct: '💥 AUTODESTRUÇÃO',
    confirm_self_destruct: 'Tem a certeza de que deseja eliminar PERMANENTEMENTE este script do servidor?',
    btn_logout: 'Sair',
    time_bomb_msg: '<h1>Acesso negado: O script expirou e foi automaticamente removido por motivos de segurança.</h1>',
    timer_text: '⏱ Tempo restante até à autodestruição: ',
    timer_destroying: 'DESTRUIÇÃO EM PROGRESSO...',
    zip_err_open: 'Não é possível abrir o ficheiro de arquivo.',
    zip_err_traversal: 'Negação de segurança: Tentativa de escrever fora da pasta permitida no arquivo (Path Traversal).',
    zip_err_exists: 'Operação abortada: O ficheiro já existe no servidor.',
    only_zip_supported: 'Os formatos suportados são: .zip, .rar, .tar.gz, .7z.',
    card_download_title: 'Download de URL & Instalador',
    card_download_desc: 'Descarregar qualquer ficheiro ou instalar automaticamente plataformas CMS populares',
    select_app: 'Selecione a aplicação / biblioteca:',
    btn_download: 'Iniciar download',
    btn_install: 'Executar instalador',
    download_url: 'URL do ficheiro:',
    download_success: 'Ficheiro descarregado com sucesso.',
    download_error: 'Erro ao descarregar o ficheiro: ',
    install_success: 'Instalação concluída com sucesso. Ficheiros extraídos e protegidos.',
    install_error: 'Erro durante a instalação: ',
    overwrite_mode: 'Modo de sobrescritura de ficheiros:',
    overwrite_skip: 'Saltar existentes',
    overwrite_all: 'Sobrescrever todos (Perigoso)',
    overwrite_older: 'Sobrescrever apenas mais antigos',
    remote_downloader_title: '1. Remote Downloader (Descarregar de URL)',
    cms_installer_title: '2. One-Click CMS & Tools Installer',
    select_app_default: '-- Selecione o sistema / biblioteca --',
    save_as: 'Guardar como (nome de ficheiro/caminho opcional):',
    placeholder_package: 'ex. package.zip',
    install_dir: 'Diretório de instalação (opcional):',
    placeholder_install_dir: 'ex. wordpress (deixar vazio para a pasta principal)',
    folders_optgroup: 'Pastas',
    zip_optgroup: 'Ficheiros ZIP',
    folder_suffix: ' (Pasta)',
    confirm_delete_title: 'Confirmar eliminação',
    btn_cancel: 'Cancelar',
    btn_delete_confirm: 'Eliminar selecionados',
    delete_success_detail: 'Itens selecionados eliminados com sucesso.',
    delete_error_detail: 'Falha ao eliminar alguns itens: ',
    operation_details: 'Detalhes da operação:',
    btn_close: 'Fechar',
    select_del_targets: 'Selecione os itens a eliminar (seleção múltipla permitida):'
  }
};
